export const FETCH_CONTACT_STARTED = "FETCH_CONTACT_STARTED";
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";
export const FETCH_CONTACT_ERROR = "FETCH_CONTACT_ERROR";

export const POST_CONTACT_SUCCESS = "POST_CONTACT_SUCCESS";

export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";

export const DELETE_CONFIRM = "DELETE_CONFIRM";
